### ISSUE TITLE
Please add a way to remove padding entirely.

### ISSUE THREAD

**Issue by rogerscg** [hvalev/py-markdown-table#4]

**Comment by hvalev** [comment]
Just don't use the argument. The default is `0` which means no padding is applied. Also, all arguments are keyword arguments and not positional ones, so you can choose which ones you use. Unless you provide some more context, I'll be closing this issue.

**Comment by hvalev** [comment]
Can you please also provide some sample input and output?

**Comment by ladd-a** [comment]
I'm not sure why @rogerscg did not provide samples, but there is certainly padding added by default even using the sample tables.

In your sample following code produces padded output with markdown code quotes.
```py
from py_markdown_table.markdown_table import markdown_table
data = [
    {
        "Product": "Smartphone",
        "Brand": "Apple",
        "Price": 999.99
    },
    {
        "Product": "Laptop",
        "Brand": "Dell",
        "Price": 1299.99
    }
]
markdown = markdown_table(data).get_markdown()
print(markdown)
```
```
```+------------------------+
|  Product |Brand| Price |
+----------+-----+-------+
|Smartphone|Apple| 999.99|
+----------+-----+-------+
|  Laptop  | Dell|1299.99|
+------------------------+```
```

And when done with `set_params(row_sep="markdown",padding_width=0,quote=False)` padding persists on all columns.
```py
from py_markdown_table.markdown_table import markdown_table
data = [
    {
        "Product": "Smartphone",
        "Brand": "Apple",
        "Price": 999.99
    },
    {
        "Product": "Laptop",
        "Brand": "Dell",
        "Price": 1299.99
    }
]
markdown = markdown_table(data).set_params(row_sep="markdown",padding_width=0,quote=False).get_markdown()
print(markdown)
```
```
|  Product |Brand| Price |
|----------|-----|-------|
|Smartphone|Apple| 999.99|
|  Laptop  | Dell|1299.99|
```
-----
Version details:
```
Windows 10 22H2 - build 19045.3693
Python version: 3.10.11 64-bit (Microsoft Store)
Pip: 23.0.1
py-markdown-table 0.4.0
Visual studio code 1.83.1 (system setup)
PSVersion 7.3.3
```

**Comment by ladd-a** [comment]
Also, why not consider using common table formatting techniques instead of manually padding columns?

As per https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables#formatting-content-within-your-table
```
| Left-aligned | Center-aligned | Right-aligned |
| :---         |     :---:      |          ---: |
| git status   | git status     | git status    |
| git diff     | git diff       | git diff      |
```
| Left-aligned | Center-aligned | Right-aligned |
| :---         |     :---:      |          ---: |
| git status   | git status     | git status    |
| git diff     | git diff       | git diff      |

Though, even the samples contain some padding at the end to make them look nicer in code blocks, so either removing all padding or sticking to one space should be sufficient.

**Comment by hvalev** [comment]
Ah, I see. This padding is added to simply even out columns so that each cell has the width of the longest element present in that column. If I understand you correctly, you'd prefer something like this:

```
|Product|Brand|Price|
|----------|-----|-------|
|Smartphone|Apple|999.99|
|Laptop|Dell|1299.99|
```

The quotes is just a convenience parameter for renderers which require quotes to indicate the beginning and ending of the markdown block.

I've reopened this issue, so let me know if I'm correct in the assumptions I've made.

As for the formatting you suggested, alas, this is only supported by the Github markdown renderer and maybe others, but afaik it is not part of the native markdown syntax.

**Comment by ladd-a** [comment]
Yes, you are inferring the meaning in my messages correctly. I realized after posting that the more correct terminology might have been "spacing" instead of "padding".

I am aware that the suggested change is not native markdown syntax but if we really get down to it, tables are not part of markdown syntax at all. So maybe add the table aligning as a new option? Many markdown renderers support it and it would leave it up to the individual to choose between manual and automatic alignments.

If I read configuration parameters correctly, there is currently no options for column alignments so this might be somewhat big undertaking to firstly enable that feature to begin with, so for the time being I would like to see just the possibility to output without any spacing as you pointed out.

**Comment by hvalev** [comment]
I'll think about the proposed change and if it really brings anything new to the table. As far as I see it, even if I omit the adding of spaces for cells in columns so that they are even, it wouldn't really change anything in how those are rendered in any markdown renderer, correct? Therefore, there is no new functional gain from this, unless someone wants to parse the output of this library, for which I'm sure there is a better representation for working with the data contained within. Let me know what your specific use-case is or if it is more of an aesthetics issue.

The other comment you made about allowing columns to be formatted individually (left, right, centerright, etc) is indeed something new and worth considering. As it stands right now this formatting is applied globally for the whole table.

**Comment by ladd-a** [comment]
I think you are correct in that not having tight formatting should theoretically not break any rendering engine.
In my personal use case I am working with rather long strings and noticed that the output was breaking, but that was due to console adding line breaks in places where they were not meant to be in.

What would most benefit from having tight tables is cases where the output needs to be sent over an middle manager such as web API. With large tables you can easily end up with large empty strings in the data payload.

**Comment by hvalev** [comment]
That's fair, but I believe it can be solved by simply stripping blank spaces from the string before sending it. Alternatively, if you have blank spaces in your data, use the `padding_char` parameter and set it to some non-standard character not present in your data, which you can later strip the same way. There is an example for `padding_char` in the description and that approach should work for your case. I think that you can understand and agree that this is neither the standard nor intended use for this library. It is meant to render small tables to clis or some markdown renderers intended to be read by a person.
